Fix error compilación prod ERROR in app/app.module.ts(51,19): Error during template compile of 'AppModule'    Function calls are not supported in decorators but 'weekdaysMin' was called.